"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2025, (parseInt("10") - 1), parseInt("18"), parseInt("14"), parseInt("55"), parseInt("10")); }
    static version() { return "unknown"; }
}
